name: rikulo_commons
version: 2.3.2
description: Common reusable Dart classes and utilities.
authors:
- Tom Yeh <tomyeh@rikulo.org>
- Henri Chen <henrichen@rikulo.org>
- Simon Pai <simonpai@rikulo.org>
homepage: http://rikulo.org
dependencies:
  logging: any
  mime: any
dev_dependencies:
  test: any
environment:
  sdk: ">=1.12.0"
