name: rikulo_commons
version: 0.8.9
description: Common reusable Dart classes and utilities.
authors:
- Tom Yeh <tomyeh@rikulo.org>
- Henri Chen <henrichen@rikulo.org>
- Simon Pai <simonpai@rikulo.org>
homepage: http://rikulo.org
dependencies:
  meta: any
  unittest: any
  logging: any
environment:
  sdk: ">=0.8.7"
