name: rikulo_commons
version: 3.2.1+1
description: Common reusable Dart classes and utilities.
authors:
- Tom Yeh <tomyeh@rikulo.org>
- Henri Chen <henrichen@rikulo.org>
- Simon Pai <simonpai@rikulo.org>
homepage: http://rikulo.org

dependencies:
  logging: any
  mime: any
  charcode: any

dev_dependencies:
  test: any

environment:
  sdk: '>=2.0.0 <3.0.0'
