name: rikulo_commons
version: 0.7.6
description: >
  Common reusable Dart classes and utilities.
authors:
- Tom Yeh <tomyeh@rikulo.org>
- Henri Chen <henrichen@rikulo.org>
- Simon Pai <simonpai@rikulo.org>
homepage: http://rikulo.org
dependencies:
  meta: any
  unittest: any
