name: rikulo_commons
version: 4.1.3
description: Common reusable Dart classes and utilities.
authors:
- Tom Yeh <tomyeh@rikulo.org>
- Henri Chen <henrichen@rikulo.org>
- Simon Pai <simonpai@rikulo.org>
homepage: http://rikulo.org
repository: https://github.com/rikulo/commons
issue_tracker: https://github.com/rikulo/commons/issues

dependencies:
  logging: any
  mime: any
  charcode: any

dev_dependencies:
  test: any

environment:
  sdk: '>=2.8.0 <3.0.0'
