name: rikulo_commons
version: 4.3.0
description: Common reusable Dart classes and utilities.
homepage: http://rikulo.org
repository: https://github.com/rikulo/commons
issue_tracker: https://github.com/rikulo/commons/issues

dependencies:
  logging: ^1.0.0
  mime: ^1.0.0
  charcode: ^1.2.0

dev_dependencies:
  test: ^1.16.3

environment:
  sdk: '>=2.8.0 <3.0.0'
